/// <reference types="expo/types" />

// Provides Expo's ambient type declarations (e.g. `*.css`, image imports) so `tsc` resolves
// Expo-specific modules. Normally auto-generated by Expo tooling and gitignored, but committed here
// so typecheck works in CI (where it would not be regenerated before `tsc` runs).
