#!/usr/bin/env bash
#
# Archive + upload to TestFlight with Xcode, with no third-party services.
#
# Why it exists: the project is in the Apple Developer Program and the distribution channel to the
# team and to the testers is TestFlight. Xcode does all the work (signing, distribution certificate,
# upload) and this script keeps the procedure reproducible and free of clicks in the Organizer. EAS
# remains a future option for building without a Mac; it is not needed for this.
#
# Usage, from app/:
#   npm run ios:testflight                       # archive + export of the .ipa (no upload)
#   ASC_KEY_ID=… ASC_ISSUER_ID=… ASC_KEY_PATH=…/AuthKey_XXXX.p8 npm run ios:testflight
#                                                # archive + direct upload to App Store Connect
#
# The API key is created once in App Store Connect → Users and Access → Integrations →
# App Store Connect API → Team Keys (the App Manager role is enough). The .p8 is downloaded ONCE:
# keep it outside the repo (e.g. ~/.private_keys/). Without the key, the .ipa stays in build/export/
# and is uploaded with Xcode → Window → Organizer → Distribute App, or with Transporter.
#
# The build number is the date-time (CFBundleVersion must grow on every upload and App Store Connect
# rejects duplicates): that way there is no need to touch app.json or commit a counter. The visible
# version (CFBundleShortVersionString) still comes from `expo.version` in app.json.
set -euo pipefail

cd "$(dirname "$0")/.."

# The native project is generated by expo prebuild from the app's name, which in the beta variant is
# a different one (app.config.js): it is discovered instead of assumed.
WORKSPACE=$(ls -d ios/*.xcworkspace 2>/dev/null | head -1 || true)
SCHEME=$(basename "${WORKSPACE:-ViroVision.xcworkspace}" .xcworkspace)
BUILD_DIR=build
ARCHIVE="$BUILD_DIR/ViroVision.xcarchive"
EXPORT_DIR="$BUILD_DIR/export"
# Overridable from CI, which needs it afterwards to assign the build to its group.
BUILD_NUMBER="${BUILD_NUMBER:-$(date +%Y%m%d%H%M)}"

if [ -z "$WORKSPACE" ] || [ ! -d "$WORKSPACE" ]; then
  echo "No ios/*.xcworkspace: run 'npx expo prebuild -p ios' first." >&2
  exit 1
fi

AUTH=()
DESTINATION=export
if [ -n "${ASC_KEY_ID:-}" ] && [ -n "${ASC_ISSUER_ID:-}" ] && [ -n "${ASC_KEY_PATH:-}" ]; then
  AUTH=(-authenticationKeyID "$ASC_KEY_ID" -authenticationKeyIssuerID "$ASC_ISSUER_ID" -authenticationKeyPath "$ASC_KEY_PATH")
  # This used to set DESTINATION=upload and xcodebuild uploaded directly; now the .ipa is always
  # exported so its entitlements can be inspected, and altool does the upload further down.
fi

echo "› Archive (build $BUILD_NUMBER)…"
# Expo writes CFBundleVersion as a literal in Info.plist (not as $(CURRENT_PROJECT_VERSION)), so
# passing the build setting to xcodebuild is not enough — measured: the first upload went out as "1".
# ios/ is a regenerable artefact, editing it here does not dirty the repo.
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "ios/$SCHEME/Info.plist"
rm -rf "$ARCHIVE"
mkdir -p "$BUILD_DIR"
# The full log goes to a file and only the tail goes to the screen; on failure the last lines are
# shown BEFORE exiting — a bare `| tail -3` swallowed the real error twice (2026-08-30).
# In CI the archive goes UNSIGNED and the export signs (using the cloud distribution one, single and
# reusable). The reason, learned the hard way on 2026-08-30: automatic archive signing uses a
# development identity, and on an ephemeral runner that created a new development certificate per run
# until the account's cap ("maximum number of certificates"; 16 had to be revoked); forcing
# CODE_SIGN_IDENTITY="Apple Distribution" does not help either — Xcode rejects it as a conflict with
# automatic signing. It only applies with an API key; on the Mac signing happens as always.
DIST=()
if [ -n "${IOS_SIGNING_PROFILE:-}" ]; then
  # MANUAL signing with the distribution certificate and the profile installed by the workflow: the
  # archive comes out signed and with ALL of the project's entitlements. The unsigned path (below)
  # exported only team-identifier and the app failed at runtime (2026-09-06). The signing settings are
  # pinned by plugins/withDevelopmentTeam.js in the app target's pbxproj during prebuild; they are not
  # passed here so they do not reach the Pods.
  DIST=()
elif [ "${#AUTH[@]}" -gt 0 ]; then
  DIST=(CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO)
fi
if ! xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release \
  -destination 'generic/platform=iOS' -archivePath "$ARCHIVE" \
  CURRENT_PROJECT_VERSION="$BUILD_NUMBER" \
  COMPILER_INDEX_STORE_ENABLE=NO \
  ${DIST[@]+"${DIST[@]}"} \
  -allowProvisioningUpdates ${AUTH[@]+"${AUTH[@]}"} archive > "$BUILD_DIR/xcodebuild-archive.log" 2>&1; then
  echo "✗ Archive failed; last lines of the log:" >&2
  tail -80 "$BUILD_DIR/xcodebuild-archive.log" >&2
  exit 65
fi
tail -3 "$BUILD_DIR/xcodebuild-archive.log"

# With an unsigned archive (the CI path), exportArchive cannot deduce the team from the archive and
# fails with "No Team Found in Archive" (run of 2026-08-30): it has to be declared in the
# ExportOptions. It is read from the pbxproj —pinned by plugins/withDevelopmentTeam.js during
# prebuild— so the ID lives in a single place. On the Mac the archive is signed and the teamID
# matches: harmless.
TEAM_ID=$(sed -n 's/.*DEVELOPMENT_TEAM = \([A-Z0-9]*\);.*/\1/p' "ios/$SCHEME.xcodeproj/project.pbxproj" | head -1)
BUNDLE_ID=$(sed -n 's/.*PRODUCT_BUNDLE_IDENTIFIER = \([^;]*\);.*/\1/p' "ios/$SCHEME.xcodeproj/project.pbxproj" | head -1 | tr -d '"')
# Manual signing (CI with our own certificate) or automatic (the developer's Mac). See above.
if [ -n "${IOS_SIGNING_PROFILE:-}" ]; then
  SIGNING_XML="<key>signingStyle</key><string>manual</string>
  <key>signingCertificate</key><string>Apple Distribution</string>
  <key>provisioningProfiles</key><dict><key>$BUNDLE_ID</key><string>$IOS_SIGNING_PROFILE</string></dict>"
else
  SIGNING_XML="<key>signingStyle</key><string>automatic</string>"
fi
if [ -z "$TEAM_ID" ]; then
  echo "No DEVELOPMENT_TEAM in the pbxproj: the prebuild did not run plugins/withDevelopmentTeam.js." >&2
  exit 64
fi

# The ExportOptions is generated here so 'destination' follows the presence of the key.
PLIST="$BUILD_DIR/ExportOptions.plist"
cat > "$PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>method</key><string>app-store-connect</string>
  <key>destination</key><string>$DESTINATION</string>
  $SIGNING_XML
  <key>teamID</key><string>${IOS_SIGNING_TEAM:-$TEAM_ID}</string>
  <key>uploadSymbols</key><true/>
  <key>manageAppVersionAndBuildNumber</key><false/>
</dict>
</plist>
PLIST

echo "› Export ($DESTINATION)…"
rm -rf "$EXPORT_DIR"
if ! xcodebuild -exportArchive -archivePath "$ARCHIVE" -exportOptionsPlist "$PLIST" \
  -exportPath "$EXPORT_DIR" -allowProvisioningUpdates ${AUTH[@]+"${AUTH[@]}"} > "$BUILD_DIR/xcodebuild-export.log" 2>&1; then
  echo "✗ Export failed; last lines of the log:" >&2
  tail -80 "$BUILD_DIR/xcodebuild-export.log" >&2
  exit 70
fi
tail -5 "$BUILD_DIR/xcodebuild-export.log"

# The .ipa's entitlements are verified BEFORE uploading. On 2026-09-06 the build uploaded "fine" and
# on the phone NEHotspotConfiguration returned "internal error": the archive goes unsigned and on
# export Apple signs with whatever the profile carries; if one of the project's entitlements did not
# make it in, nobody sees it until the app fails out on the street. Every entitlement that requires a
# capability goes here.
REQUIRED_ENTITLEMENTS=(com.apple.developer.networking.HotspotConfiguration)
IPA=$(ls "$EXPORT_DIR"/*.ipa | head -1)
INSPECTION="$BUILD_DIR/ipa-inspection"
rm -rf "$INSPECTION" && mkdir -p "$INSPECTION"
unzip -q "$IPA" -d "$INSPECTION"
APP=$(ls -d "$INSPECTION"/Payload/*.app | head -1)
IPA_ENTITLEMENTS=$(codesign -d --entitlements :- "$APP" 2>/dev/null || true)
echo "› Entitlements of the .ipa:"
echo "$IPA_ENTITLEMENTS" | grep -oE 'com\.apple\.developer\.[A-Za-z0-9.-]+' | sort -u | sed 's/^/    /'
for e in "${REQUIRED_ENTITLEMENTS[@]}"; do
  if ! echo "$IPA_ENTITLEMENTS" | grep -q "$e"; then
    echo "✗ The .ipa does not carry the $e entitlement: the app would fail at runtime (\"internal error\" when joining the WiFi). Not uploading." >&2
    echo "  Check that the capability is enabled on the App ID and that the signature includes it (docs/dev-build-ios.md)." >&2
    exit 72
  fi
done
echo "✓ Required entitlements present."

if [ "${#AUTH[@]}" -gt 0 ]; then
  echo "› Uploading to App Store Connect…"
  # altool looks for the key in ./private_keys, ~/private_keys, ~/.private_keys or API_PRIVATE_KEYS_DIR.
  KEYS_DIR=$(mktemp -d) && cp "$ASC_KEY_PATH" "$KEYS_DIR/AuthKey_$ASC_KEY_ID.p8"
  if ! API_PRIVATE_KEYS_DIR="$KEYS_DIR" xcrun altool --upload-app -f "$IPA" -t ios \
      --apiKey "$ASC_KEY_ID" --apiIssuer "$ASC_ISSUER_ID" > "$BUILD_DIR/altool-upload.log" 2>&1; then
    echo "✗ Upload failed; last lines of the log:" >&2
    tail -40 "$BUILD_DIR/altool-upload.log" >&2
    exit 74
  fi
  echo "✓ Build $BUILD_NUMBER uploaded to App Store Connect. It shows up in TestFlight in a few minutes (Apple processing)."
else
  echo "✓ IPA in $EXPORT_DIR. Upload it with Xcode → Window → Organizer → Distribute App, or export ASC_KEY_ID/ASC_ISSUER_ID/ASC_KEY_PATH to upload directly."
fi
