/**
 * Who sends the events: a phone and a session.
 *
 * **`phone` is an anonymous identifier generated by the app**, not the IMEI, not the advertising id,
 * nothing from the system: a random number stored in AsyncStorage the first time. It does not
 * identify a person, it identifies an installation, which is all that is needed to know whether two
 * failures come from the same unit. It is lost on uninstall, and losing it is fine.
 *
 * **`session` changes on every app start.** It is what makes it possible to reconstruct "what
 * happened that time": the events of a failed attempt are the ones sharing a session, and without
 * that a table with several days of use cannot be read.
 */
import AsyncStorage from '@react-native-async-storage/async-storage';

export const PHONE_KEY = 'virovision.telemetry.phone';

/**
 * A short random identifier. `Math.random` is enough: it protects nothing, it only has to avoid
 * colliding between the project's handful of phones, and pulling in a UUID dependency for that is
 * not worth it.
 */
export function generateId(prefix: string, random: () => number = Math.random): string {
  const part = () => Math.floor(random() * 0xffffffff).toString(16).padStart(8, '0');
  return `${prefix}-${part()}${part()}`;
}

/**
 * Reads the stored id or creates one. On any AsyncStorage failure it returns an ephemeral one
 * instead of breaking: losing continuity across sessions is far cheaper than losing the telemetry.
 */
export async function getPhoneId(
  storage: Pick<typeof AsyncStorage, 'getItem' | 'setItem'> = AsyncStorage,
  random: () => number = Math.random
): Promise<string> {
  try {
    const stored = await storage.getItem(PHONE_KEY);
    if (stored) return stored;
    const fresh = generateId('phone', random);
    await storage.setItem(PHONE_KEY, fresh);
    return fresh;
  } catch {
    return generateId('phone-ephemeral', random);
  }
}
